apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: citus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Thay đổi dung lượng lưu trữ tùy ý
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: citus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "tuanta2021@gmail.com"   # Thay bằng email bạn muốn
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "password"               # Thay bằng mật khẩu bạn muốn
          volumeMounts:
            - mountPath: /var/lib/pgadmin     # Đường dẫn pgAdmin lưu dữ liệu
              name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: citus
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
