apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: bigdata   
spec:
  selector:
    app: hiveserver2
  ports:
    - name: hive-rpc
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: hive-ui
      protocol: TCP
      port: 10002
      targetPort: 10002