apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiveserver2
  template:
    metadata:
      labels:
        app: hiveserver2
    spec:
      containers:
      - name: hiveserver2
        image: apache/hive:4.0.0
        ports:
        - containerPort: 10000
        - containerPort: 10002
        env:
        - name: SERVICE_NAME
          value: "hiveserver2"
        - name: IS_RESUME
          value: "true"
        - name: VERBOSE
          value: "true"
        - name: HADOOP_USER_NAME
          value: "hadoop"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true          
        volumeMounts:          
        - name: hive-config-volume
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml  
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml  
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
          subPath: yarn-site.xml  
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
          subPath: mapred-site.xml  
      volumes:
      - name: hive-config-volume
        configMap:
          name: hive-config    
      - name: hadoop-config-volume
        configMap:
          name: hadoop-config   
