apiVersion: v1
kind: Pod
metadata:
  name: copy-pod
  namespace: keycloak
spec:
  containers:
  - name: network-tools-container
    image: praqma/network-multitool
    command: ["/bin/sh", "-c", "sleep infinity"]
    stdin: true
    tty: true
    volumeMounts:
    - name: my-pvc-volume
      mountPath: /mnt/data  # Mount PVC vào đường dẫn trong Pod
  volumes:
  - name: my-pvc-volume
    persistentVolumeClaim:
      claimName: jar-pvc  # Tên PVC của bạn
