{{- if (.Values.persistence.enabled) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "ignite.fullname" . }}-wal-storage-class
  namespace: {{ include "ignite.fullname" . }}
provisioner: {{ .Values.persistence.walVolume.provisioner }}
#parameters:
#{{ toYaml .Values.persistence.walVolume.provisionerParameters | indent 2 }}
{{- end }}
